/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Customer: {
            id: string;
            customerId: string;
            companyName: string;
            email?: string;
            street?: string;
            city?: string;
            plz?: string;
            phone?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            contactPersons: components["schemas"]["ContactPerson"][];
            offers: components["schemas"]["Offer"][];
            orders: components["schemas"]["Order"][];
            users: components["schemas"]["User"][];
            tariffCustomers: components["schemas"]["TariffCustomer"][];
        };
        ContactPerson: {
            id: string;
            customerId: string;
            customer: components["schemas"]["Customer"];
            salutation: string;
            firstName: string;
            lastName: string;
            email?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            offers: components["schemas"]["Offer"][];
            orders: components["schemas"]["Order"][];
        };
        Document: {
            id: string;
            /** Format: int32 */
            version: number;
            displayName?: string;
            pdfReady: boolean;
            docxReady: boolean;
            status: components["schemas"]["DocumentStatus"];
            isCurrent: boolean;
            offer?: components["schemas"]["Offer"];
            offerId?: string;
            order?: components["schemas"]["Order"];
            orderId?: string;
            taskId?: string;
            task?: components["schemas"]["Task"];
            /** Format: date-time */
            createdAt: string;
        };
        Task: {
            id: string;
            jobId?: string;
            status: components["schemas"]["TaskStatus"];
            target: components["schemas"]["TaskTarget"];
            type: components["schemas"]["TaskType"];
            error?: string;
            document?: components["schemas"]["Document"];
            offerReservation?: components["schemas"]["Offer"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Offer: {
            id: string;
            supplier?: components["schemas"]["Supplier"];
            supplierId?: string;
            customer: components["schemas"]["Customer"];
            customerId: string;
            customerContactPerson: components["schemas"]["ContactPerson"];
            contactPersonId: string;
            user: components["schemas"]["User"];
            userId: string;
            quoteId: string;
            paymentTerm: string;
            /** Format: date-time */
            date: string;
            /** Format: date-time */
            validUntil?: string;
            /** Format: date-time */
            requestFrom?: string;
            offerFlatRates: components["schemas"]["OfferFlatRate"][];
            offerPositions: components["schemas"]["OfferPosition"][];
            documents: components["schemas"]["Document"][];
            orders?: components["schemas"]["Order"];
            isReserved: boolean;
            reservationTaskId?: string;
            reservationTask?: components["schemas"]["Task"];
            /** Format: int32 */
            net_amount: number;
            /** Format: int32 */
            version: number;
            revisions: components["schemas"]["OfferRevision"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OfferRevision: {
            id: string;
            offer: components["schemas"]["Offer"];
            offerId: string;
            /** Format: int32 */
            version: number;
            snapshot: Record<string, never>;
            changedBy?: string;
            /** Format: date-time */
            createdAt: string;
        };
        OfferPosition: {
            id: string;
            offer: components["schemas"]["Offer"];
            offerId: string;
            product: components["schemas"]["Product"];
            productId: string;
            contract: components["schemas"]["Contract"];
            contractId: string;
            /** Format: int32 */
            duration_months: number;
            /** Format: int32 */
            quantity: number;
            optional?: boolean;
            /** Format: int32 */
            total_cents: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OfferFlatRate: {
            id: string;
            flatRate: components["schemas"]["FlatRate"];
            flatRateId: string;
            offer: components["schemas"]["Offer"];
            offerId: string;
            /** Format: int32 */
            quantity: number;
            /** Format: int32 */
            total_cents: number;
        };
        Order: {
            id: string;
            orderId: string;
            /** Format: date-time */
            date: string;
            paymentTerm: string;
            projectId: string;
            customer: components["schemas"]["Customer"];
            customerId: string;
            supplier?: components["schemas"]["Supplier"];
            supplierId?: string;
            offer: components["schemas"]["Offer"];
            offerId: string;
            customerContactPerson: components["schemas"]["ContactPerson"];
            contactPersonId: string;
            employee: components["schemas"]["User"];
            employeeId: string;
            orderPositions: components["schemas"]["OrderPosition"][];
            documents: components["schemas"]["Document"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OrderPosition: {
            id: string;
            order: components["schemas"]["Order"];
            orderId: string;
            product: components["schemas"]["Product"];
            productId: string;
            contract: components["schemas"]["Contract"];
            contractId: string;
            /** Format: int32 */
            duration_months: number;
            /** Format: int32 */
            quantity: number;
            /** Format: int32 */
            unit_price: number;
            /** Format: int32 */
            discount: number;
            /** Format: int32 */
            total: number;
            /** Format: date-time */
            createdAt: string;
        };
        Product: {
            id: string;
            name: string;
            description?: string;
            table?: string;
            orderPositions: components["schemas"]["OrderPosition"][];
            offerPositions: components["schemas"]["OfferPosition"][];
            tariff?: components["schemas"]["Tariff"];
            tariffId?: string;
            tariffCustomers: components["schemas"]["TariffCustomer"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Tariff: {
            id: string;
            products: components["schemas"]["Product"][];
            configs: components["schemas"]["TariffConfig"][];
            customers: components["schemas"]["TariffCustomer"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TariffConfig: {
            id: string;
            tariff: components["schemas"]["Tariff"];
            tariffId: string;
            contract: components["schemas"]["Contract"];
            contractId: string;
            /** Format: int32 */
            duration: number;
            /** Format: int32 */
            min_quantity: number;
            /** Format: int32 */
            max_quantity?: number;
            /** Format: int32 */
            price: number;
        };
        TariffCustomer: {
            id: string;
            tariff: components["schemas"]["Tariff"];
            tariffId: string;
            product: components["schemas"]["Product"];
            productId: string;
            contract: components["schemas"]["Contract"];
            contractId: string;
            customer: components["schemas"]["Customer"];
            customerId: string;
            /** Format: int32 */
            duration: number;
            /** Format: int32 */
            min_quantity: number;
            /** Format: int32 */
            max_quantity?: number;
            /** Format: int32 */
            price: number;
        };
        User: {
            id: string;
            name: string;
            salutation: string;
            firstName: string;
            lastName: string;
            phone?: string;
            email: string;
            emailVerified: boolean;
            image?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sessions: components["schemas"]["Session"][];
            accounts: components["schemas"]["Account"][];
            role?: string;
            banned?: boolean;
            banReason?: string;
            /** Format: date-time */
            banExpires?: string;
            customer?: components["schemas"]["Customer"];
            customerId?: string;
            offers: components["schemas"]["Offer"][];
            orders: components["schemas"]["Order"][];
        };
        Session: {
            id: string;
            /** Format: date-time */
            expiresAt: string;
            token: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            ipAddress?: string;
            userAgent?: string;
            userId: string;
            user: components["schemas"]["User"];
            impersonatedBy?: string;
        };
        Account: {
            id: string;
            accountId: string;
            providerId: string;
            userId: string;
            user: components["schemas"]["User"];
            accessToken?: string;
            refreshToken?: string;
            idToken?: string;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
            /** Format: date-time */
            refreshTokenExpiresAt?: string;
            scope?: string;
            password?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Verification: {
            id: string;
            identifier: string;
            value: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Supplier: {
            id: string;
            supplierId: string;
            name: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            offers: components["schemas"]["Offer"][];
            orders: components["schemas"]["Order"][];
        };
        FlatRate: {
            id: string;
            name: string;
            table: string;
            /** Format: int32 */
            total_cents: number;
            offerFlatRates: components["schemas"]["OfferFlatRate"][];
        };
        AppSetting: {
            key: string;
            value: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Contract: {
            id: string;
            name: string;
            features: string[];
            table: string;
            orderPositions: components["schemas"]["OrderPosition"][];
            offerPositions: components["schemas"]["OfferPosition"][];
            tariffConfigs: components["schemas"]["TariffConfig"][];
            tariffCustomers: components["schemas"]["TariffCustomer"][];
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        DocumentStatus: "UPLOADED" | "UPLOADING" | "GENERATED" | "PROCESSING" | "PENDING" | "FAILED";
        /** @enum {string} */
        TaskStatus: "COMPLETED" | "RUNNING" | "PENDING" | "FAILED";
        /** @enum {string} */
        TaskTarget: "OFFER" | "ORDER" | "RENEWAL";
        /** @enum {string} */
        TaskType: "UPLOAD" | "RESERVATION" | "GENERATION";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
