openapi: 3.1.0
info:
  title: Prisma API
  description: ""
  version: 1.0.0
paths: {}
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        companyName:
          type: string
        email:
          type: string
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"
        contactPersons:
          type: array
          items:
            $ref: "#/components/schemas/ContactPerson"
        street:
          type: string
        city:
          type: string
        plz:
          type: string
        phone:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
      required:
        - id
        - customerId
        - companyName
        - orders
        - contactPersons
        - offers
        - users
    ContactPerson:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        customer:
          $ref: "#/components/schemas/Customer"
        salutation:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
      required:
        - id
        - customerId
        - customer
        - salutation
        - firstName
        - lastName
        - offers
    Document:
      type: object
      properties:
        id:
          type: string
        version:
          type: integer
          format: int32
        displayName:
          type: string
        pdfReady:
          type: boolean
        docxReady:
          type: boolean
        status:
          $ref: "#/components/schemas/DocumentStatus"
        isCurrent:
          type: boolean
        offer:
          $ref: "#/components/schemas/Offer"
        offerId:
          type: string
        order:
          $ref: "#/components/schemas/Order"
        orderId:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - version
        - pdfReady
        - docxReady
        - status
        - isCurrent
        - createdAt
    Task:
      type: object
      properties:
        id:
          type: string
        jobId:
          type: string
        status:
          $ref: "#/components/schemas/TaskStatus"
        type:
          $ref: "#/components/schemas/TaskType"
        offer:
          $ref: "#/components/schemas/Offer"
        offerId:
          type: string
        order:
          $ref: "#/components/schemas/Order"
        orderId:
          type: string
        error:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - status
        - type
        - createdAt
        - updatedAt
    Offer:
      type: object
      properties:
        id:
          type: string
        supplier:
          $ref: "#/components/schemas/Supplier"
        supplierId:
          type: string
        customer:
          $ref: "#/components/schemas/Customer"
        customerId:
          type: string
        customerContactPerson:
          $ref: "#/components/schemas/ContactPerson"
        contactPersonId:
          type: string
        user:
          $ref: "#/components/schemas/User"
        userId:
          type: string
        voucherId:
          type: string
        paymentTerm:
          type: string
        date:
          type: string
          format: date-time
        validUntil:
          type: string
          format: date-time
        requestFrom:
          type: string
          format: date-time
        offerFlatRates:
          type: array
          items:
            $ref: "#/components/schemas/OfferFlatRate"
        offerPositions:
          type: array
          items:
            $ref: "#/components/schemas/OfferPosition"
        order:
          $ref: "#/components/schemas/Order"
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"
        net_amount:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - customer
        - customerId
        - customerContactPerson
        - contactPersonId
        - user
        - userId
        - voucherId
        - paymentTerm
        - date
        - offerFlatRates
        - offerPositions
        - documents
        - tasks
        - net_amount
        - createdAt
        - updatedAt
    OfferPosition:
      type: object
      properties:
        id:
          type: string
        offer:
          $ref: "#/components/schemas/Offer"
        offerId:
          type: string
        product:
          $ref: "#/components/schemas/Product"
        productId:
          type: string
        contract:
          $ref: "#/components/schemas/Contract"
        contractId:
          type: string
        duration_months:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        optional:
          type: boolean
        total_cents:
          type: integer
          format: int32
        tax_rate:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - offer
        - offerId
        - product
        - productId
        - contract
        - contractId
        - duration_months
        - quantity
        - total_cents
        - tax_rate
    OfferFlatRate:
      type: object
      properties:
        id:
          type: string
        flatRate:
          $ref: "#/components/schemas/FlatRate"
        flatRateId:
          type: string
        offer:
          $ref: "#/components/schemas/Offer"
        offerId:
          type: string
        quantity:
          type: integer
          format: int32
        total_cents:
          type: integer
          format: int32
      required:
        - id
        - flatRate
        - flatRateId
        - offer
        - offerId
        - quantity
        - total_cents
    Order:
      type: object
      properties:
        id:
          type: string
        customer:
          $ref: "#/components/schemas/Customer"
        customerId:
          type: string
        user:
          $ref: "#/components/schemas/User"
        userId:
          type: string
        orderPositions:
          type: array
          items:
            $ref: "#/components/schemas/OrderPosition"
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"
        offer:
          $ref: "#/components/schemas/Offer"
        offerId:
          type: string
        employee:
          $ref: "#/components/schemas/User"
        employeeId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - customer
        - customerId
        - user
        - userId
        - orderPositions
        - documents
        - tasks
    OrderPosition:
      type: object
      properties:
        id:
          type: string
        order:
          $ref: "#/components/schemas/Order"
        orderId:
          type: string
        product:
          $ref: "#/components/schemas/Product"
        productId:
          type: string
        contract:
          $ref: "#/components/schemas/Contract"
        contractId:
          type: string
        duration_months:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        priceAtPurchase:
          type: number
          format: double
        currency:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - order
        - orderId
        - product
        - productId
        - contract
        - contractId
        - duration_months
        - quantity
        - priceAtPurchase
        - currency
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        table:
          type: string
        productPricing:
          type: array
          items:
            $ref: "#/components/schemas/ProductPricing"
        orderPositions:
          type: array
          items:
            $ref: "#/components/schemas/OrderPosition"
        offerPositions:
          type: array
          items:
            $ref: "#/components/schemas/OfferPosition"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - productPricing
        - orderPositions
        - offerPositions
    ProductPricing:
      type: object
      properties:
        id:
          type: string
        contract:
          $ref: "#/components/schemas/Contract"
        contractId:
          type: string
        product:
          $ref: "#/components/schemas/Product"
        productId:
          type: string
        min_quantity:
          type: integer
          format: int32
        max_quantity:
          type: integer
          format: int32
        duration_months:
          type: integer
          format: int32
        price:
          type: integer
          format: int32
      required:
        - id
        - contract
        - contractId
        - product
        - productId
        - min_quantity
        - duration_months
        - price
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        salutation:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        email:
          type: string
        emailVerified:
          type: boolean
        image:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        sessions:
          type: array
          items:
            $ref: "#/components/schemas/Session"
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/Account"
        role:
          type: string
        banned:
          type: boolean
        banReason:
          type: string
        banExpires:
          type: string
          format: date-time
        employeeOrders:
          type: array
          items:
            $ref: "#/components/schemas/Order"
        customer:
          $ref: "#/components/schemas/Customer"
        customerId:
          type: string
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"
      required:
        - id
        - name
        - salutation
        - firstName
        - lastName
        - email
        - emailVerified
        - createdAt
        - updatedAt
        - sessions
        - accounts
        - employeeOrders
        - offers
        - orders
    Session:
      type: object
      properties:
        id:
          type: string
        expiresAt:
          type: string
          format: date-time
        token:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        ipAddress:
          type: string
        userAgent:
          type: string
        userId:
          type: string
        user:
          $ref: "#/components/schemas/User"
        impersonatedBy:
          type: string
      required:
        - id
        - expiresAt
        - token
        - createdAt
        - updatedAt
        - userId
        - user
    Account:
      type: object
      properties:
        id:
          type: string
        accountId:
          type: string
        providerId:
          type: string
        userId:
          type: string
        user:
          $ref: "#/components/schemas/User"
        accessToken:
          type: string
        refreshToken:
          type: string
        idToken:
          type: string
        accessTokenExpiresAt:
          type: string
          format: date-time
        refreshTokenExpiresAt:
          type: string
          format: date-time
        scope:
          type: string
        password:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - accountId
        - providerId
        - userId
        - user
        - createdAt
        - updatedAt
    Verification:
      type: object
      properties:
        id:
          type: string
        identifier:
          type: string
        value:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - identifier
        - value
        - expiresAt
    Supplier:
      type: object
      properties:
        id:
          type: string
        supplierId:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
      required:
        - id
        - supplierId
        - name
        - offers
    FlatRate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        table:
          type: string
        total_cents:
          type: integer
          format: int32
        offerFlatRates:
          type: array
          items:
            $ref: "#/components/schemas/OfferFlatRate"
      required:
        - id
        - name
        - table
        - total_cents
        - offerFlatRates
    Contract:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        features:
          type: array
          items:
            type: string
        productPricing:
          type: array
          items:
            $ref: "#/components/schemas/ProductPricing"
        orderPositions:
          type: array
          items:
            $ref: "#/components/schemas/OrderPosition"
        offerPositions:
          type: array
          items:
            $ref: "#/components/schemas/OfferPosition"
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - features
        - productPricing
        - orderPositions
        - offerPositions
    DocumentStatus:
      type: string
      enum:
        - UPLOADED
        - UPLOADING
        - GENERATED
        - PROCESSING
        - PENDING
        - FAILED
    TaskStatus:
      type: string
      enum:
        - COMPLETED
        - RUNNING
        - PENDING
        - FAILED
    TaskType:
      type: string
      enum:
        - OFFER
        - ORDER
        - RENEWAL
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers: []
