/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as UserPathlessLayoutRouteRouteImport } from './routes/user/_pathlessLayout/route'
import { Route as UserPathlessLayoutIndexRouteImport } from './routes/user/_pathlessLayout/index'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products/$productId/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as UserPathlessLayoutSettingsIndexRouteImport } from './routes/user/_pathlessLayout/settings/index'
import { Route as UserPathlessLayoutOrdersIndexRouteImport } from './routes/user/_pathlessLayout/orders/index'
import { Route as UserPathlessLayoutAdminIndexRouteImport } from './routes/user/_pathlessLayout/admin/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPathlessLayoutRouteRoute = UserPathlessLayoutRouteRouteImport.update({
  id: '/user/_pathlessLayout',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPathlessLayoutIndexRoute = UserPathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserPathlessLayoutRouteRoute,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const UserPathlessLayoutSettingsIndexRoute =
  UserPathlessLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => UserPathlessLayoutRouteRoute,
  } as any)
const UserPathlessLayoutOrdersIndexRoute =
  UserPathlessLayoutOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => UserPathlessLayoutRouteRoute,
  } as any)
const UserPathlessLayoutAdminIndexRoute =
  UserPathlessLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => UserPathlessLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserPathlessLayoutRouteRouteWithChildren
  '/checkout/': typeof CheckoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/user/': typeof UserPathlessLayoutIndexRoute
  '/user/admin/': typeof UserPathlessLayoutAdminIndexRoute
  '/user/orders/': typeof UserPathlessLayoutOrdersIndexRoute
  '/user/settings/': typeof UserPathlessLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/products': typeof ProductsIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
  '/user': typeof UserPathlessLayoutIndexRoute
  '/user/admin': typeof UserPathlessLayoutAdminIndexRoute
  '/user/orders': typeof UserPathlessLayoutOrdersIndexRoute
  '/user/settings': typeof UserPathlessLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/user/_pathlessLayout': typeof UserPathlessLayoutRouteRouteWithChildren
  '/checkout/': typeof CheckoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/user/_pathlessLayout/': typeof UserPathlessLayoutIndexRoute
  '/user/_pathlessLayout/admin/': typeof UserPathlessLayoutAdminIndexRoute
  '/user/_pathlessLayout/orders/': typeof UserPathlessLayoutOrdersIndexRoute
  '/user/_pathlessLayout/settings/': typeof UserPathlessLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/checkout/'
    | '/login/'
    | '/products/'
    | '/signup/'
    | '/dashboard/'
    | '/products/$productId/'
    | '/user/'
    | '/user/admin/'
    | '/user/orders/'
    | '/user/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/products'
    | '/signup'
    | '/dashboard'
    | '/products/$productId'
    | '/user'
    | '/user/admin'
    | '/user/orders'
    | '/user/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/user/_pathlessLayout'
    | '/checkout/'
    | '/login/'
    | '/products/'
    | '/signup/'
    | '/_authenticated/dashboard/'
    | '/products/$productId/'
    | '/user/_pathlessLayout/'
    | '/user/_pathlessLayout/admin/'
    | '/user/_pathlessLayout/orders/'
    | '/user/_pathlessLayout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UserPathlessLayoutRouteRoute: typeof UserPathlessLayoutRouteRouteWithChildren
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_pathlessLayout': {
      id: '/user/_pathlessLayout'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserPathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_pathlessLayout/': {
      id: '/user/_pathlessLayout/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserPathlessLayoutIndexRouteImport
      parentRoute: typeof UserPathlessLayoutRouteRoute
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/user/_pathlessLayout/settings/': {
      id: '/user/_pathlessLayout/settings/'
      path: '/settings'
      fullPath: '/user/settings/'
      preLoaderRoute: typeof UserPathlessLayoutSettingsIndexRouteImport
      parentRoute: typeof UserPathlessLayoutRouteRoute
    }
    '/user/_pathlessLayout/orders/': {
      id: '/user/_pathlessLayout/orders/'
      path: '/orders'
      fullPath: '/user/orders/'
      preLoaderRoute: typeof UserPathlessLayoutOrdersIndexRouteImport
      parentRoute: typeof UserPathlessLayoutRouteRoute
    }
    '/user/_pathlessLayout/admin/': {
      id: '/user/_pathlessLayout/admin/'
      path: '/admin'
      fullPath: '/user/admin/'
      preLoaderRoute: typeof UserPathlessLayoutAdminIndexRouteImport
      parentRoute: typeof UserPathlessLayoutRouteRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UserPathlessLayoutRouteRouteChildren {
  UserPathlessLayoutIndexRoute: typeof UserPathlessLayoutIndexRoute
  UserPathlessLayoutAdminIndexRoute: typeof UserPathlessLayoutAdminIndexRoute
  UserPathlessLayoutOrdersIndexRoute: typeof UserPathlessLayoutOrdersIndexRoute
  UserPathlessLayoutSettingsIndexRoute: typeof UserPathlessLayoutSettingsIndexRoute
}

const UserPathlessLayoutRouteRouteChildren: UserPathlessLayoutRouteRouteChildren =
  {
    UserPathlessLayoutIndexRoute: UserPathlessLayoutIndexRoute,
    UserPathlessLayoutAdminIndexRoute: UserPathlessLayoutAdminIndexRoute,
    UserPathlessLayoutOrdersIndexRoute: UserPathlessLayoutOrdersIndexRoute,
    UserPathlessLayoutSettingsIndexRoute: UserPathlessLayoutSettingsIndexRoute,
  }

const UserPathlessLayoutRouteRouteWithChildren =
  UserPathlessLayoutRouteRoute._addFileChildren(
    UserPathlessLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UserPathlessLayoutRouteRoute: UserPathlessLayoutRouteRouteWithChildren,
  CheckoutIndexRoute: CheckoutIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
