import type { OfferTemplate } from "../schemas/templates/offer.template.schema.js";
import { serializeAcceptedOfferSnapshot } from "../schemas/accepted-offer.js";
const now = new Date("2026-09-08T12:00:00.000Z");
const timestamps = { createdAt: now, updatedAt: now };
export const sourceFixture = () => ({
    supplierId: null,
    customerId: "customer",
    contactPersonId: "contact",
    employeeId: "user",
    contractId: "contract",
    duration_months: 12,
    paymentTerm: "30 Tage",
    language: "EN" as const,
    validUntil: null,
    requestFrom: null,
    net_amount: 90000,
    customer: {
        id: "customer",
        customerId: "C-1",
        companyName: "Original Ltd",
        language: "DE" as const,
        email: null,
        invoiceEmail: null,
        phone: null,
        street: "Original street",
        city: null,
        zip: null,
        country: "Deutschland",
        currency: "EUR",
        taxRate: 19,
        salutation: null,
        ...timestamps,
    },
    customerContactPerson: {
        id: "contact",
        customerId: "customer",
        salutation: null,
        firstName: "First",
        lastName: "Last",
        email: null,
        ...timestamps,
    },
    employee: {
        id: "user",
        name: "Test User",
        salutation: "",
        firstName: "Test",
        lastName: "User",
        email: "test@example.com",
        phone: null,
        ...timestamps,
    },
    contract: {
        id: "contract",
        translations: [
            {
                language: "EN" as const,
                name: "Original contract",
                features: ["original"],
                table: "Terms",
            },
        ],
        ...timestamps,
    },
    positions: [
        {
            id: "position",
            productId: "product",
            quantity: 10,
            optional: false,
            total_cents: 120000,
            discount_cents: 30000,
            free_months: 3,
            eur_user_month: 1000,
            tariffVersionId: null,
            createdAt: now,
            updatedAt: now,
            product: {
                id: "product",
                translations: [
                    {
                        language: "EN" as const,
                        name: "Original product",
                        description: "Product description",
                        table: "Product table",
                    },
                ],
                ...timestamps,
            },
        },
    ],
    flatRates: [
        {
            id: "flat",
            flatRateId: "flat-rate",
            quantity: 1,
            total_cents: 10000,
            flatRate: {
                id: "flat-rate",
                total_cents: 10000,
                translations: [
                    {
                        language: "EN" as const,
                        name: "Setup",
                        table: "Setup content",
                    },
                ],
                ...timestamps,
            },
        },
    ],
    discounts: [
        {
            id: "discount",
            ...timestamps,
            title: "Offer discount",
            description: null,
            amount_cents: 10000,
        },
    ],
});
export const templateFixture = (): OfferTemplate => ({
    quoteId: "Q-1",
    date: null,
    paymentTerm: "30 Tage",
    validUntil: null,
    requestFrom: null,
    supplierId: null,
    compare: false,
    customer: {
        id: "C-1",
        companyName: "Original Ltd",
        street: "Original street",
        zip: null,
        city: null,
        fullName: "First Last",
        salutation: null,
        firstName: "First",
        lastName: "Last",
        phone: null,
        email: null,
    },
    employee: {
        fullName: "Test User",
        salutation: "",
        firstName: "Test",
        lastName: "User",
        phone: null,
        email: "test@example.com",
    },
    product_names: "Original product",
    products: [],
    groups: [],
    tables: [],
    discounts: [],
});
export const offerFixture = () => {
    const s = sourceFixture();
    return {
        ...s,
        id: "offer",
        userId: s.employeeId,
        user: s.employee,
        quoteId: "Q-1",
        date: now,
        featureComparison: false,
        toCompare: [],
        offerPositions: s.positions,
        offerFlatRates: s.flatRates,
        offerDiscounts: s.discounts,
        version: 1,
        documentVersion: 0,
        acceptedAt: null,
        acceptedSnapshot: null,
        renewedFromOfferId: null,
        derivationType: null,
        ...timestamps,
    };
};
export const orderFixture = () => ({
    id: "order",
    offerId: "offer",
    orderId: "AB-2026-001",
    date: now,
    projectNumber: "P-1",
    projectDescription: "Description",
    orderDetails: "Registration",
    version: 1,
    documentVersion: 0,
    acceptedAt: now,
    acceptedById: "user",
    cancelledAt: null,
    documents: [],
    ...timestamps,
    offer: {
        ...offerFixture(),
        acceptedAt: now,
        acceptedSnapshot: serializeAcceptedOfferSnapshot(
            sourceFixture(),
            templateFixture(),
        ),
    },
});
